#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01 server

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy for load balancing
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak  # Backup the original configuration

cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

# Restart HAProxy service
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
